#[allow(non_camel_case_types)]
pub enum Vouchers {
    OVERSTOCK_NORM,
    OVERSTOCK_PLUS,
    CLEARANCE_SALE,
    LIQUIDATION,
    HONE,
    GLOW_UP,
    REROLL_SURPLUS,
    REROLL_GLUT,
    CRYSTAL_BALL,
    OMEN_GLOBE,
    TELESCOPE,
    OBSERVATORY,
    GRABBER,
    NACHO_TONG,
    WASTEFUL,
    RECYCLOMANCY,
    TAROT_MERCHANT,
    TAROT_TYCOON,
    PLANET_MERCHANT,
    PLANET_TYCOON,
    SEED_MONEY,
    MONEY_TREE,
    BLANK,
    ANTIMATTER,
    MAGIC_TRICK,
    ILLUSION,
    HIEROGLYPH,
    PETROGLYPH,
    DIRECTORS_CUT,
    RETCON,
    PAINT_BRUSH,
    PALETTE,    
}

pub fn get_min_max() -> (f64, f64) {
    (Vouchers.OVERSTOCK_NORM, Vouchers.PALETTE)
}